import {useEffect,useState,type FormEvent} from 'react';
import {Mail,LockKeyhole} from 'lucide-react';
import {studentArenaSlides} from './slides';
import {request,parseStudent,loginConfigured,previewLogin,type Student} from './auth';
export default function Login({onLogin}:{onLogin:(s:Student)=>void}){
 const [slide,setSlide]=useState(0),[username,setUsername]=useState(''),[password,setPassword]=useState(''),[remember,setRemember]=useState(true),[visible,setVisible]=useState(false),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;const t=setInterval(()=>setSlide(v=>(v+1)%studentArenaSlides.length),6200);return()=>clearInterval(t);},[]);
 async function submit(e:FormEvent){e.preventDefault();if(!username.trim()||!password)return;if(!loginConfigured){onLogin(previewLogin(username.trim(),remember));setPassword('');return;}setBusy(true);setMessage('');try{const result=await request('/session',{username:username.trim(),password,remember});onLogin(parseStudent(result.student));setPassword('');}catch(error){setMessage(error instanceof Error?error.message:'Sign-in failed. Please try again.');}finally{setBusy(false);}}
 return <main className="arena-page"><section className="arena-shell" aria-label="Student login"><div className="arena-showcase">{studentArenaSlides.map((s,i)=><article className={'arena-slide '+(i===slide?'active':'')} key={s.image} aria-hidden={i!==slide}><img src={s.image} alt=""/><div className="arena-slide-shade"/><div className="arena-slide-copy"><p>{s.eyebrow}</p><h1>{s.title}</h1><span>{s.body}</span></div></article>)}<div className="arena-slide-controls">{studentArenaSlides.map((s,i)=><button key={s.image} className={i===slide?'active':''} aria-label={'Show '+s.eyebrow} aria-pressed={i===slide} onClick={()=>setSlide(i)}/>)}</div></div><div className="arena-auth-panel"><form className="arena-login" onSubmit={submit}><span className="arena-kicker">Student Login</span><h2>Welcome back.</h2><p>Continue your practice, challenges and learning progress.</p>{!loginConfigured&&<div role="status"><p>Preview with sample data. Student account sign-in is not available yet.</p><button type="button" className="arena-primary" onClick={()=>onLogin(previewLogin('preview',false))}>Explore sample account</button><p>Do not enter a real password in this preview.</p></div>}<label className="arena-field"><span>Email or student username</span><div className="arena-input-field"><span className="arena-field-icon"><Mail size={20} aria-hidden="true"/></span><input autoComplete="username" required value={username} onChange={e=>setUsername(e.target.value)} placeholder="student@mga.edu.mm"/></div></label><label className="arena-field"><span>Password</span><div className="arena-password-field"><span className="arena-field-icon"><LockKeyhole size={20} aria-hidden="true"/></span><input type={visible?'text':'password'} autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)} placeholder="Enter your password"/><button type="button" aria-label={visible?'Hide password':'Show password'} onClick={()=>setVisible(v=>!v)}>{visible?'Hide':'Show'}</button></div></label><div className="arena-login-options"><label><input type="checkbox" checked={remember} onChange={e=>setRemember(e.target.checked)}/> Remember me</label><button type="button" onClick={()=>setMessage('Please contact your school administrator to verify your identity and reset your password.')}>Need a password reset?</button></div>{message&&<p className="login-message" role="alert">{message}</p>}<button className="arena-primary" disabled={busy}>{busy?'Signing in…':'Log in →'}</button><p className="arena-new-student">New student? <button type="button" onClick={()=>setMessage('Your school administrator will help you enroll and create your account.')}>Contact administrator for admission</button></p><p className="arena-help-note">Need help? Contact your school administrator.</p></form></div></section></main>;
}
